### ISSUE TITLE
Distribution via PyPI

### ISSUE THREAD

**Issue by MagnusBieneck** [makerplane/pyAvTools#8]
I would suggest to upload this package to PyPI, so it can be easier consumed (e.g., by pyEfis). First step would be a manual approach, but for the long term, we could also automate it via Github actions: For every tag one pushes, there will be a wheel published to PyPI. What do you think?

**Comment by birkelbach** [comment]
I agree but I've not done that before and I have very little bandwidth right now.  A big headache for new users has been making sure that his module is installed.  I was thinking about getting rid of this module altogether but I'd like to keep it if possible.  It'd be nice if it were in PyPI so that it could automatically be installed.

**Comment by MagnusBieneck** [comment]
Alright, if you are fine with it, I can create a project on PyPI and push the wheel.

**Comment by MagnusBieneck** [comment]
Here we go: https://pypi.org/project/pyavtools/. I had to fix some minor stuff to make PyPI accept the wheel. By default, I am now the owner of the project on PyPI. If you have accounts on PyPI, let me know your user names, so I can add you as owners/maintainers.

**Comment by birkelbach** [comment]
Excellent!  Thanks.  My username is 'birkelbach'

**Comment by birkelbach** [comment]
Excellent!  Thanks.  My username is 'birkelbach'
